# This is a basic workflow to help you get started with Actions

name: manual_eploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Clone supercharge website repository
        uses: actions/checkout@v2
  
      # This part here is cloning a second repository
      # While cloning the repository:
      #   - it clones the repo into the given `path`
      #   - it checks out the branch defined at `ref`
      - name: Clone supercharge docs repository
        uses: AngryPancake/vps@main
        with:
          repository: AngryPancake/vps
          path: ~/vps

      - name: Access cloned repository content
        run: |
          echo "ROOT"
          pwd
          ls -la
          echo "CLONED REPO"
          cd poc-github-actions
          ls -la


#       - name: Clone AngryPancake/vps PUBLIC repository
#         uses: AngryPancake/vps@main
#         with:
#           owner: 'AngryPancake'
#           repository: 'vps'
#       - name: Access cloned repository content
#         run: |
#           echo "ROOT"
#           pwd
#           ls -la
#           echo "CLONED REPO"
#           cd poc-github-actions
#           ls -la
